title: Nnenna Eze # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Email: nnenna.eze777@gmail.com
  <br>
  Current Location: Boston, MA **Open to alternate locations
  <br>
  Interested in: Data Science and Analytics, Data Engineering, Music and Management, Fields in conjunction with music and data
  <br><br>
  <p>I am very interested in combining my data analysis skills with my passion for the creative arts. My experience with software and data engineering includes a 2 year rotational program through John Hancock, where I first worked as a full stack engineer, and eventually took on more leadership through facilitating daily production support meetings and collaborating with business analysts on client requests. I then transitioned to a role within the data team, where I analyzed data mappings and used data visualization tools to better portray the data. This experience sparked my interest in data, prompting me to deepen my knowledge of machine learning and data analysis tools. I still have much to learn, but am enthusiastic and always looking for self improvement. Beyond my technical expertise I have hands-on experience in the music industry. I play several instruments myself, and have learned more everyday working for a local performance venue in my neighborhood. I have learned so much through this role, and love to learn more everyday. **Find out more on my resume
  <p>
  <br><br>
  <a href="https://www.linkedin.com/in/nnenna-eze-0b268616a/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
